export const employeeData = [
  {
    id: 1,
    name: "John",
    emailId: "john@companyname.com",
    aadharNumber: "3653782476",
    panNumber: "R05HKI2BHY",
    employeeType: "Full-Time",
    joiningDate: "18-02-2019",
  },
  {
    id: 2,
    name: "Gulnar",
    emailId: "gulnar@companyname.com",
    aadharNumber: "5864636979",
    panNumber: "JU3XUBVXFI",
    employeeType: "Part-Time",
    joiningDate: "09-04-2019",
  },
  {
    id: 3,
    name: "Maxene",
    emailId: "maxene@companyname.com",
    aadharNumber: "4439662981",
    panNumber: "ZSIW4XGXWX",
    employeeType: "Part-Time",
    joiningDate: "04-06-2019",
  },
  {
    id: 4,
    name: "Joanna",
    emailId: "joanna@companyname.com",
    aadharNumber: "8992106113",
    panNumber: "TRQ5GOSEKQ",
    employeeType: "Full-Time",
    joiningDate: "10-11-2019",
  },
];
